<?php /* Clinic */ ?>
<?php
	if( ( $clinic_id = Mage::getSingleton('customer/session')->getClinicId() ) !== false ){

		$clinic = Mage::getModel('customer/customer')->load( $clinic_id );
		$customer_group = Mage::getModel('customer/group')->load( $clinic->getGroupId() );

		if( $customer_group->getCustomerGroupCode() == 'Clinic' ){

			$clinic_customers = Mage::getResourceModel('customer/customer_collection')
				->addFieldToFilter( 'clinic_id', $clinic->getId() );

			$current_customer_id = Mage::getSingleton('customer/session')->getCustomer()->getId();

?>
		<div class="clinic-container">
			<div class="clinic">
				<div class="clinic-bar">Welcome <?php echo $clinic->getName(); ?></div>
				<div class="clinic-customer-chooser">
					Shopping for:
					<select onchange="window.location=this.value;">
						<option value="<?php echo Mage::getUrl(); ?>customer/account/logout">New Customer</option>
						<option value="<?php echo Mage::getUrl(); ?>nutrigineering/index/loginAs/?customer_id=<?php echo $clinic->getId(); ?>"<?php echo $current_customer_id == $clinic->getId() ? ' selected="selected"' : ''; ?>>Clinic (Self)</option>
						<?php foreach( $clinic_customers as $clinic_customer ){ $clinic_customer->load(); ?>
							<option value="<?php echo Mage::getUrl(); ?>nutrigineering/index/loginAs/?customer_id=<?php echo $clinic_customer->getId(); ?>"<?php echo $current_customer_id == $clinic_customer->getId() ? ' selected="selected"' : ''; ?>><?php echo $clinic_customer->getName(); ?></option>
						<?php } ?>
					</select>
				</div>
				<div class="clinic-actions">
					<a href="<?php echo Mage::getUrl(); ?>nutrigineering/index/logout/">Clinic Logout</a>
				</div>
				<div style="clear:both;"></div>
			</div>
		</div>
		<style>
		.nav-primary .menu-active > ul.level0 {
			margin-top:143px;
		}
		</style>
	<?php } ?>
<?php } ?>
<?php /* END Clinic */ ?>