<div class="slider-top">
	<div class="top-container-bg slide1">
		<div class="page-header">
		<h2>WE ARE <br>
		NUTRIGINEERING</h2>
		<p>
		We are a science based nutrition and  wellness company that<br>
		equips individuals for optimal health.</p>

		<a href="https://www.nutrigineering.com/about-us" class="button button-black">About Us</a>
		</div>
	</div>

	<div class="top-container-bg slide2">
		<div class="page-header">
		<div class="left-content">
                  <h3>Webinars</h3>
                  <p>Understand the science behind the nutrition of functional medicine through a series of webinars hosted by Dr. Rayms</p>
                  <a href="https://www.nutrigineering.com/webinars" class="button button-black">Get Started Now</a>
         </div>


		</div>
	</div>
	<div class="top-container-bg slide3">
		<div class="page-header">
		<div class="left-content">
                  <h3>EVENTS</h3>
                  <p>See the effectiveness of proper nutrition live and in person at one of our events.</p>
                  <a href="https://www.nutrigineering.com/events" class="button button-black">Get Started Now</a>
         </div>
		</div>
	</div>

	<div class="top-container-bg slide4">
		<div class="page-header">
		<h2>BLOG</h2>
		<p> Learn about the root causes and effects of <br>chronic diseases through various articles<br> written by Dr. Rayms.</p>

		<a href="https://www.nutrigineering.com/blog" class="button button-black">Read More</a>
		</div>
	</div>

	<div class="top-container-bg slide5">
		<div class="page-header">
				  <div class="left-content">
                  <h3>ELIMINATION DIET</h3>
                  <p>Our 21 Day Elimination Diet is guaranteed to decrease the toxic load on your body’s systems by up to half.</p>
                  <a href="https://www.nutrigineering.com/elimination-diet-program.html" class="button button-black">Get Started Now</a>
         </div>
		</div>
	</div>		

</div>

<script type="text/javascript">
jQuery('.slider-top').slick({
  dots: true,
  infinite: true,
  speed: 500,
  fade: true,
  cssEase: 'linear',
   autoplay: true,
  autoplaySpeed: 5000
});	

</script>