<div id="messages_product_view"><?php echo $this->getMessagesBlock()->toHtml() ?></div>


<div class="row">
	<div class="columns large-12 small-12">
		<div class="page-title">
			<h1><?php echo Mage::helper('contacts')->__('Contact Info') ?></h1>
		</div>
	   </div>

	<div class="columns large-5 small-12">
		<p><b>Address:</b>
		<br>
		Unit 701, Page 1 Building, 1215, <br>
		Acacia Avenue, Madrigal Business Park, <br>
		Ayala Alabang, Muntinlupa 1780
	    </p>
		<p><b>Phone:</b>
		<br>
			<a href="tel:639175121038">+63 917 512 1038</a><br>
			<a href="+63 9175372624">+63 917 537 2624</a>

	    </p>	 
	    <p><b>Email:</b>
	    <br>
		<a href="mailto:support@nutrigineering.com">support@nutrigineering.com</a>
		</p>
	</div>
	<div class="columns large-7 small-12">


		<form action="<?php echo $this->getFormAction(); ?>" id="contactForm" method="post">

	<div class="large-6 small-12 columns">
		<input name="name" id="name" placeholder="Name" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('contacts')->__('Name')) ?>" value="<?php echo $this->escapeHtml($this->helper('contacts')->getUserName()) ?>" class="input-text required-entry" type="text" />

	</div>
	<div class="large-6 small-12 columns">
		<input name="email" id="email" placeholder="Email" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('contacts')->__('Email')) ?>" value="<?php echo $this->escapeHtml($this->helper('contacts')->getUserEmail()) ?>" class="input-text required-entry validate-email" type="text" />
	</div>
	<div class="large-12 small-12 columns">
		<input name="telephone" id="telephone" placeholder="Telephone" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('contacts')->__('Telephone')) ?>" value="" class="input-text" type="text" />

	</div>
	<div class="large-12 small-12 columns">
		
		<textarea name="comment" id="comment" placeholder="Comment" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('contacts')->__('Comment')) ?>" class="required-entry input-text"></textarea>

	</div>
	<div class="large-12 columns small-12" style="text-align: center;">

		<input type="text" name="hideit" id="hideit" value="" style="display:none !important;" />
		<a href="#" class="button button-black trigger-sub">Send Message</a>
		<button type="submit" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('contacts')->__('Submit')) ?>" class="button" style="display: none;"><span><span><?php echo Mage::helper('contacts')->__('Submit') ?></span></span></button>
		
	</div>
	
				


	
		</form>
		<script type="text/javascript">
		//<![CDATA[
			var contactForm = new VarienForm('contactForm', true);
		//]]>
		</script>
		<script type="text/javascript">
			jQuery(document).ready(function(){
				jQuery('a.trigger-sub').click(function(){
					jQuery('button.trigger-sub').trigger( "click" );
				});
			});
		</script>		

	</div>
</div>

<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d4664.68798623974!2d121.0209460035414!3d14.424254054984877!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3397d1cf3d5a2803%3A0x3056fd235c907a06!2sPage+1+Building!5e0!3m2!1sen!2sph!4v1520250798681" width="100%" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>